### ISSUE TITLE
Countdown starts too early

### ISSUE THREAD

**Issue by sklafg** [mikemountain/nfl-led-scoreboard#12]
My board shows the countdown for the last hour until kick-off but the kick-off is in 3 hours.

**Comment by mikemountain** [comment]
Is it like this for every 1pm game or just a particular one? What timezone are you in, and do you have it set on your board?

**Comment by sklafg** [comment]
I didn't check every 1pm game but more than one had the bug.
My timezone is CEST. 
My timezone is correctly set to CEST on the board.

**Comment by mikemountain** [comment]
I think this should have been fixed in one of the more recent merges, if this is still an issue, please re-open!
