### ISSUE TITLE
displaying wrong favorite team for playoffs

### ISSUE THREAD

**Issue by machinasdei** [mikemountain/nfl-led-scoreboard#17]
got a weird one here, so it displays the game Saturday for 1:05PM for IND vs BUF , but my favorite team is set to WSH - which did work vs the iggles last week.  Why would it display the wrong teams for the preview of the next weeks' game?

**Comment by mikemountain** [comment]
ah sorry about that, I started this last year during the playoffs so I just wanted to keep testing it with whichever team was currently playing/playing next - also, I think it might crash if a fav team is set that's not in the playoffs. gimme a few mins to make a quick patch branch

**Comment by mikemountain** [comment]
hey @machinasdei, let me know if this fixes the issue - if not feel free to reopen this issue and berate me!

**Comment by machinasdei** [comment]
Hey man, i'll try out the b/fix playoff teams now!  Just wanted to note that I tried changing the favorite team to anyone in the current playoffs and it kept showing that IND vs BUF game

**Comment by machinasdei** [comment]
@mikemountain thanks Mike!  I edited the files with your fixes.  It is now displaying WSH vs TB correctly now.  Thank you.
Would it be possible to rotate through the rest of the scheduled games too as if your favorite team is NOT in the playoffs?  Just a wish, but not sure if its an easy fix or not, again really appreciate the quick fix for this one! thanks!
