### ISSUE TITLE
Board doesn't transition from pregame->live or live->postgame without rerunning

### ISSUE THREAD

**Issue by tjhall9** [mikemountain/nfl-led-scoreboard#29]
Running with `sudo ... &`, program will stay on the pregame screen until the script is restarted manually, same things happen postgame where the final score didn't appear until manual restart. Would love to leave it running and have it automatically transition between states without user input.

**Comment by WashCaps33** [comment]
Either I’m doing something wrong or something is off, but I know the WFT have a game tonight and I am still getting errors.  So I’m lost.

**Comment by tjhall9** [comment]
The next preseason games aren't until 8/12

**Comment by mikemountain** [comment]
@tjhall9 I noticed this too, thanks for confirming it's the same with the final score/endgame situation. Will definitely look into it for next week's games.

@WashCaps33 have you pulled the latest master branch? I see the end screen for last night's game when I boot up.

**Comment by WashCaps33** [comment]
Well damn.  Shows how much I care about the preseason. Lol sorry about that

**Comment by WashCaps33** [comment]
Trying this today seeing as it is a game day for the WFT and while I get no error messages, I do get a “Schedule State, waiting 30” message and nothing happens.  Is this normal?

**Comment by tjhall9** [comment]
Yeah that's normal. It may not actually show the live game without an update once the game starts though

**Comment by WashCaps33** [comment]
Ahhh.  Thanks for the info!

**Comment by mikemountain** [comment]
Think I've fixed this on this branch https://github.com/mikemountain/nfl-led-scoreboard/tree/b/fix-pre-post-game-transition-states but I'll be testing with the real game before merging it in, just to be sure

**Comment by WashCaps33** [comment]
I must be doing something wrong.  Now that the game has started, it’s updating every 3 seconds, but nothing is appearing on the LED board.

**Comment by mikemountain** [comment]
@WashCaps33 can you post the output of the script? You might need to kill and restart the script, my new bugfix isn't in yet and there was an issue with the game time in it

**Comment by WashCaps33** [comment]
It just continuously updates.  The script works as it should, just nothing transmitting to the board.

**Comment by pjockey** [comment]
What is the updating process? I tried the git commands, but got a bunch of errors.

**Comment by tjhall9** [comment]
@mikemountain my board is still stuck without showing the final screen again, I wasn't home when the game started but it was running live when I got back and not sitting in scheduled. So it looks like it's halfway there

**Comment by tjhall9** [comment]
@mikemountain transition to final state worked at the end of CAR-IND. Not sure why it didn't happen with the games previously
