### ISSUE TITLE
Why am I getting this when I try to sudo git pull

### ISSUE THREAD

**Issue by Bombsurace** [mikemountain/nfl-led-scoreboard#35]
Updating 8f324fa..40d0d0e
error: Your local changes to the following files would be overwritten by merge:
        config.json
Please commit your changes or stash them before you merge.
Aborting

if i try and git stash i get this

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'pi@football.(none)')
Cannot save the current index state

**Comment by mikemountain** [comment]
Did you run the commands it told you to? You don't have to specifically set your email or name if you don't want to, git just wants to make sure changes are tracked properly.

Run the commands like it tells you to, can even be verbatim, and then try stashing again.

**Comment by Bombsurace** [comment]
Got it, I thought I somehow was accessing something I wasn't suppose to.  Never had to add that stuff in there before so was super confused.  Followed the steps and all good.  You're awesome as always good sir, thanks for reaching out to dumb dumbs like me lol
