### ISSUE TITLE
Pre game logos centering

### ISSUE THREAD

**Issue by Bombsurace** [mikemountain/nfl-led-scoreboard#7]
![IMG_20200914_175033](https://user-images.githubusercontent.com/70653215/93152243-0879cb80-f6b3-11ea-92a5-6637c3afbcc6.jpg)

Is there a way to get the logos in the pre game more centered on each side? Seems to be off to the right on both sides. 

In game they are perfectly aligned and all that.

**Comment by mikemountain** [comment]
Can you pull master just to make sure you've got the latest stuff? I've been tweaking the logo placement config because the logos end up funky like that, the TEN Pre-away x value should be 1.

**Comment by Bombsurace** [comment]
Looks good, spacing doesn't look to overlap anymore

**Comment by mikemountain** [comment]
Great, thanks. I'm gonna keep this issue open because I'm positive other teams will have messy pre-game placements so this can be for people to notify me if they catch something funky

**Comment by Bombsurace** [comment]
![16002635757054293476490843026323](https://user-images.githubusercontent.com/70653215/93345254-70313300-f7e7-11ea-8d21-d7fd3c6f0a8d.jpg)

Just pulled it up this morning seeing when the update for the new week starts . Jag logo looks like the "bad" logos from before still and with the blurry on the edges dips onto the VS part

**Comment by mikemountain** [comment]
hey @Bombsurace, do you still have this issue? The logo currently looks okay on my board, do you have the latest version pulled?

**Comment by Bombsurace** [comment]
I'll try and check sometime tonight or tomorrow after work. It still looks like the "bad" logo from before. 

I did restart my scoreboard this morning to double check, is that the same as a new "pull" or do I need to run and update on my side?

**Comment by mikemountain** [comment]
Unless you have a start-up script that does a pull then no, you'll have to run `git pull` to get the latest code

**Comment by Bombsurace** [comment]
Got it, may have to add a git pull into my start up script then.  

Logo is updated and looks solid (at least on the post game screen currently).  Thank you .  I'll keep an eye out for any other logos that maybe be wonky .  Thank you good sir

**Comment by Bombsurace** [comment]
![IMG_20200923_100228](https://user-images.githubusercontent.com/70653215/94045202-fcad9980-fd83-11ea-874b-38440a0379e8.jpg)

Jags home logo pre game a little off? Like you said before maybe just 1 over? Looks clean though. Not sure why it says Sundays at 10 for a Thursday game but the countdown normally starts on time.

**Comment by mikemountain** [comment]
yeah, just need to play with the pre-home and pre-away values for both teams in the 64_32config file. I definitely messed up the gametime calculation somewhere along the way because there are a ton of issues with it, I'll try to take a look at this tonight and figure it out

**Comment by mikemountain** [comment]
Logos have been standardized across all teams, and should be centred properly now as of the latest change
